version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack:3.8
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=ap-south-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  interview-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD=etl_pass
      - POSTGRES_DB=etl_db

